### ISSUE TITLE
Extract text fails on the simplest of setups

### ISSUE THREAD

**Issue by zgredzik** [webpack/extract-text-webpack-plugin#317] opened 2016-12-27 10:55 UTC
Link to a minimal example: https://github.com/zgredzik/extract-text-plugin-test

Works fine when using just the `css-loader`

Using: (tried installing dependencies both via npm and yarn)
node: `6.9.1`
webpack: fails on both `2.1.0-beta.28` and `2.2.0-rc.2` as well as some older versions
extract-text-webpack-plugin: `2.0.0-beta.4`

It seems to have problems parsing the css file https://github.com/zgredzik/extract-text-plugin-test/blob/master/EVIL_DUMP

I might be doing something wrong, so I'd appreciate any hints and/or suggestions.

**Comment by mohsen1** [comment] 2016-12-31 21:27
Pass array of loaders to `extract` function.

```
                use: 
                    ExtractTextPlugin.extract([{
                        loader: 'css-loader'
                    }])
```
instead of 
```
use: [
                    ExtractTextPlugin.extract({
                        loader: 'css-loader'
                    })
                    // 'css-loader',
 ]
```

**Comment by zgredzik** [comment] 2017-01-02 06:54
Nope, that does not fix the problem. I'm not sure it even should, since the usage example shows:
```js
loader: ExtractTextPlugin.extract({
                fallbackLoader: "style-loader",
                loader: "css-loader"
            })
```
which basically is an alias for:
```
use: [ExtractTextPlugin.extract({
                fallbackLoader: "style-loader",
                loader: "css-loader"
            })]
```
according to [the docs](https://webpack.js.org/configuration/module/#rule-loader)

**Comment by bebraw** [comment] 2017-01-09 13:54
Duplicate of #265. See that issue for the workaround.

**Closed by bebraw** 2017-01-09 13:54 UTC
Labels: bug, webpack-2
