### ISSUE TITLE
[webpack v2]: broken with new `use` syntax

### ISSUE THREAD

**Issue by mrtnbroder** [webpack/extract-text-webpack-plugin#297] opened 2016-12-01 09:36 UTC
When I try to use this plugin like before, just using the new webpack v2 syntax (`loaders` -> `rules`, nested `loaders` -> `use`), this plugin breaks. Not sure it's intended, but it would be great if one would get an appropriate error message that this plugin should be used with `loader: ExtractTextWebpackPlugin.extract(...)` instead of `use: ExtractTextWebpackPlugin.extract(...)`

**Comment by TomDeBacker** [comment] 2016-12-07 00:06
@mrtnbroder Thank you for writing this here! I have been migrating from webpack 1 -> 2 and this issue cost me way too much time..

**Comment by bebraw** [comment] 2016-12-15 02:56
Closing as a duplicate of #265. Thanks for the report, though.

**Closed by bebraw** 2016-12-15 02:56 UTC
