### ISSUE TITLE
Why plugin works with Rule.loader but does not work with Rule.use?

### ISSUE THREAD

**Issue by TuiKiken** [webpack/extract-text-webpack-plugin#329] opened 2017-01-08 21:52 UTC
Why

```
{
  test: /\.css$/,
  loader: ExtractTextPlugin.extract(),
}
```

works as expected, but 

```
{
  test: /\.css$/,
  use: [
    ExtractTextPlugin.extract()
  ]
}
```

or 

```
{
  test: /\.css$/,
  use: [
    { loader: ExtractTextPlugin.extract() }
  ]
}
```

throws errors?

**Comment by bebraw** [comment] 2017-01-09 06:23
Duplicate of #265. Closing. See that issue for more details.

**Closed by bebraw** 2017-01-09 06:23 UTC
