### ISSUE TITLE
Module parse failed error for SCSS file

### ISSUE THREAD

**Issue by bellizio** [webpack/extract-text-webpack-plugin#342] opened 2017-01-19 13:52 UTC
After updating to the webpack 2.2.0 final release, I'm experiencing the following issue:

```
ERROR in ./src/assets/css/app.scss
Module parse failed: /Users/dbellizio/Dev/misc./bellizio.github.io/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!style-loader!css-loader?{"minimize":true}!postcss-loader!sass-loader!/Users/dbellizio/Dev/misc./bellizio.github.io/src/assets/css/app.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @charset 'utf-8';
|
| .main-wrapper {
 @ ./src/app/app.component.ts 11:0-32
 @ ./dist/src/app/app.component.ngfactory.ts
 @ ./dist/src/app/app.module.ngfactory.ts
 @ ./src/app/main.ts

ERROR in ./src/assets/css/app.scss
Module build failed: ModuleParseError: Module parse failed: /Users/dbellizio/Dev/misc./bellizio.github.io/src/assets/css/app.scss Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.
| @charset 'utf-8';
|
| .main-wrapper {
    at /Users/dbellizio/Dev/misc./bellizio.github.io/node_modules/webpack/lib/NormalModule.js:208:34
    at /Users/dbellizio/Dev/misc./bellizio.github.io/node_modules/webpack/lib/NormalModule.js:162:10
    at /Users/dbellizio/Dev/misc./bellizio.github.io/node_modules/loader-runner/lib/LoaderRunner.js:365:3
    at iterateNormalLoaders (/Users/dbellizio/Dev/misc./bellizio.github.io/node_modules/loader-runner/lib/LoaderRunner.js:206:10)
    at /Users/dbellizio/Dev/misc./bellizio.github.io/node_modules/loader-runner/lib/LoaderRunner.js:197:4
    at /Users/dbellizio/Dev/misc./bellizio.github.io/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:62:14
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

ERROR in /Users/dbellizio/Dev/misc./bellizio.github.io/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!style-loader!css-loader?{"minimize":true}!postcss-loader!sass-loader!/Users/dbellizio/Dev/misc./bellizio.github.io/src/assets/css/app.scss doesn't export content
Child src/app/home/home.component.html:
       [0] ./src/app/home/home.component.html 101 bytes {0} [built]
            factory:166ms building:11ms = 177ms
Child src/app/app.component.html:
       [0] ./src/app/app.component.html 111 bytes {0} [built]
            factory:29ms building:168ms = 197ms
Child src/app/about/about.component.html:
       [0] ./src/app/about/about.component.html 102 bytes {0} [built]
            factory:166ms building:31ms = 197ms
Child src/app/_global/header/header.component.html:
       [0] ./src/app/_global/header/header.component.html 99 bytes {0} [built]
            factory:169ms building:32ms = 201ms
Child src/app/_global/footer/footer.component.html:
       [0] ./src/app/_global/footer/footer.component.html 50 bytes {0} [built]
            factory:168ms building:34ms = 202ms
Child html-webpack-plugin for "index.html":
       [0] ./~/html-webpack-plugin/lib/loader.js!./src/index.html 285 bytes {0} [built]
            factory:698ms building:1360ms = 2058ms
Child extract-text-webpack-plugin:
       [0] ./src/assets/css/app.scss 247 bytes {0} [built] [failed] [1 error]
            factory:1ms building:3ms = 4ms

    ERROR in ./src/assets/css/app.scss
    Module parse failed: /Users/dbellizio/Dev/misc./bellizio.github.io/src/assets/css/app.scss Unexpected character '@' (1:0)
    You may need an appropriate loader to handle this file type.
    | @charset 'utf-8';
    |
    | .main-wrapper {
```
Here is my webpack config:

```
var webpack = require('webpack');
var webpackMerge = require('webpack-merge');
var ExtractTextPlugin = require('extract-text-webpack-plugin');
var ngToolsWebpack = require('@ngtools/webpack');
var commonConfig = require('./webpack.common.js');
var helpers = require('./helpers');

const ENV = process.env.NODE_ENV = process.env.ENV = 'production';

module.exports = webpackMerge(commonConfig, {
  output: {
    path: helpers.root('dist'),
    publicPath: '/',
    filename: '[name].[hash].js',
    chunkFilename: '[id].[hash].chunk.js'
  },

  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/\.(spec|e2e)\.ts$/],
        use: '@ngtools/webpack'
      },
      {
        test: /\.scss$/,
        include: helpers.root('src', 'assets', 'css'),
        use: ExtractTextPlugin.extract({
          fallbackLoader: 'style-loader',
          loader: [
            { loader: 'css-loader',
              query: {
                minimize: true
              }
            },
            { loader: 'postcss-loader' },
            { loader: 'sass-loader' }
          ]
        })
      }
    ]
  },

  plugins: [
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.optimize.UglifyJsPlugin({ // https://github.com/angular/angular/issues/10618
      mangle: {
        keep_fnames: true
      }
    }),
    new webpack.LoaderOptionsPlugin({
      options: {
        htmlLoader: {
         minimize: false // workaround for ng2
        }
      }
    }),
    new ExtractTextPlugin('assets/css/[name].[hash].css'),
    new webpack.DefinePlugin({
      'process.env': {
        'ENV': JSON.stringify(ENV)
      }
    }),
    new ngToolsWebpack.AotPlugin({
      tsConfigPath: helpers.root('tsconfig.json'),
      entryModule: helpers.root('src', 'app', 'app.module#AppModule'),
      mainPath: helpers.root('src', 'app', 'main.ts')
    })
  ]
});
```

**Any idea why these errors are being thrown or how to resolve them?**

**Comment by roymiloh** [comment] 2017-01-19 22:10
`use: ExtractTextPlugin.extract({ ...` -> `loader: ExtractTextPlugin.extract({ ...`

**Comment by bellizio** [comment] 2017-01-20 13:38
@roymiloh that did the trick. I was using 'loader' prior to updating, but the [webpack migration guide](https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules) specifies 'use' as the new syntax. I guess there is something in the plugin code that does not jive with the new syntax. I will switch back to using 'loader' for the time being.

**Comment by bebraw** [comment] 2017-01-21 10:48
Closing at duplicate of #265.

**Closed by bebraw** 2017-01-21 10:48 UTC
