### ISSUE TITLE
Error when using with MinChunkSizePlugin

### ISSUE THREAD

**Issue by Anahkiasen** [webpack/extract-text-webpack-plugin#115] opened 2015-10-10 19:49 UTC
I'm not sure why, when I enable the MinChunkSizePlugin I get this error:

```
TypeError: Cannot read property 'initial' of undefined
    at ExtractTextPlugin.<anonymous> (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/extract-text-webpack-plugin/index.js:22:8)
    at Array.forEach (native)
    at ExtractTextPlugin.mergeNonInitialChunks (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/extract-text-webpack-plugin/index.js:21:16)
    at ExtractTextPlugin.<anonymous> (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/extract-text-webpack-plugin/index.js:276:12)
    at Array.forEach (native)
    at ExtractTextPlugin.<anonymous> (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/extract-text-webpack-plugin/index.js:274:21)
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:52:16
    at done (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:248:21)
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:44:16
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/extract-text-webpack-plugin/index.js:270:6
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:52:16
    at done (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:248:21)
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:44:16
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/extract-text-webpack-plugin/index.js:267:13
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:187:20
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:239:13
    at _arrayEach (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:91:13)
    at _each (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:215:22)
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/extract-text-webpack-plugin/index.js:241:11
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:187:20
    at /Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:239:13
    at _arrayEach (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:91:13)
    at _each (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:82:13)
    at Object.async.forEachOf.async.eachOf (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:238:9)
    at Object.async.forEach.async.each (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/async/lib/async.js:215:22)
    at ExtractTextPlugin.<anonymous> (/Users/anahkiasen/Sites/madewithlove/madewithlove-webpack-config/node_modules/extract-text-webpack-plugin/index.js:238:10)
    at Compilation.applyPluginsAsync (/Users/anahkiasen/Sites/madewithlove/clinical-case-creator/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.seal (/Users/anahkiasen/Sites/madewithlove/clinical-case-creator/node_modules/webpack/lib/Compilation.js:524:7)
```

When I comment it out everything works fine, any idea where it could come from?

**Comment by wmaurer** [comment] 2015-10-18 15:36
I'm getting the same error, but only with a 'production' build, i.e.:

```
var production = process.env.NODE_ENV === 'production';

module.exports = {
    debug:   !production,
    devtool: production ? false : 'eval',
    ...
};
```

**Comment by mnpenner** [comment] 2015-12-15 21:16
:+1: 

When I remove `CommonsChunkPlugin` it runs, but I kinda need `CommonsChunkPlugin`.

**Comment by KSDaemon** [comment] 2016-01-08 22:17
+1. Getting same error in production mode.

**Comment by ianwalter** [comment] 2016-01-13 22:55
@mnpenner It seems to work with `AggressiveMergingPlugin` for me in production. Still having this problem?

**Comment by mnpenner** [comment] 2016-01-14 17:32
@ianwalter Well, not any more. Just tried it again and it's compiling fine with `AggressiveMergingPlugin` enabled now. I recently updated my dependencies though, maybe something changed? I swear I tested it correctly before.

`MinChunkSizePlugin` still isn't working though :-)

**Comment by mamapitufo** [comment] 2016-01-19 14:20
I am having the same issue. If I pause it in the debugger, `mergeNonInitialChunks` will get a chunk that has a 1-element array (in my case) in the `chunk.chunks` property. The element in the array is `undefined`. This is what throws an error in line 21. As far as I can tell, this is added in line 219, because `chunks.indexOf(c)` returns `-1`. As noted by everyone else, this only happens when running the "production build", so with any optimization plugins that might change the number of chunks enabled.

I was following the example in [this post](http://blog.madewithlove.be/post/webpack-your-bags/), and this happened at the "Extraction" sub heading. My software: node v4.2.1, extract-text-webpack-plugin v1.0.1.

**Comment by weinot** [comment] 2016-01-20 03:34
@mamapitufo +1
Is there any solution for this issue?

I met this problem when using 
new webpack.optimize.CommonsChunkPlugin({
      names: ['app'],
      children: true,
      minChunks: 2
    }),

**Comment by Peeneye** [comment] 2016-02-01 15:36
So, for me, this broke only when the chunks I had were less than the minChunkSize threshold, which, if you were following the madewithlove blog post, will be the case when you do a production build.  If you set that to something really tiny, it works.  As a temporary workaround, add the following line after line 21 in extract-text-webpack-plugin/index.js: `if (typeof c === 'undefined') return;`

**Comment by mnpenner** [comment] 2016-02-02 17:20
Aha! That would explain why it started working for me @Peeneye

**Comment by dYb** [comment] 2016-02-28 13:07
Works for me. Still not available on the npm? why not publish a new package.

**Comment by Growiel** [comment] 2016-03-14 03:20
Just lost a lot of time on the same issue. Please publish a new version as soon as possible, I don't like having custom code in modules.

**Comment by cellvia** [comment] 2016-03-23 18:39
bump! can someone do this?

**Comment by arthinking** [comment] 2016-03-29 13:56
May be just a bug. All I could do now is add the defensive code customer, hope will be fixed next version.
`chunk.chunks.forEach(function(c) {
    if (typeof c === 'undefined') return;  // prevent undefined error`

**Comment by prachikhadke** [comment] 2016-04-08 17:40
Any solutions/workarounds for this?

**Comment by RabidFX** [comment] 2016-04-08 18:53
I just committed a fix to this on[ my fork](https://github.com/RabidFX/extract-text-webpack-plugin) of the extract-text-webpack-plugin. 

However, it's not fully tested, so the [pull request](https://github.com/webpack/extract-text-webpack-plugin/pull/170) does not pass code coverage metrics. I'll try to add some extra tests soon, and to have my fix merged in production. In the meantime, feel free to use my fork, but remember it's not thoroughly tested. 

As far as I'm concerned, it works normally, and fixed this particular issue.

**Comment by szarouski** [comment] 2016-04-10 03:37
So basically in my case in has nothing to do with plugins as same configuration works for some projects, but doesn't work for others (I'm working in a multi-project environment). The reason why it is breaking for me is because I'm having a require.ensure code block which is relying on require.context. 
Example:
```js
const requireContext = require.context("./data-scripts/", true, /^\.\/.*\.js$/);
const requireMap = requireContext.keys().reduce(function(memo, pathInContext) {
    var dataScriptName = pathInContext.replace(/(^\.\/|\.js$)/g, '');
    memo[dataScriptName] = requireContext(pathInContext);
    return memo;
}, {});
```
then later in code:
```js
require.ensure([], function() {
    const requireResult = requireMap[dependency].default;
    //...more code
});
```
I think this code is valid, but it looks like extract-text-webpack-plugin doesn't like it too much. I think it is not a huge issue for me as I can rewrite the code to not use context. Still it sounds like a bug which can be fixed. @sokra, would you like me to provide a sample project which reproduce the issue? Thanks.

**Comment by szarouski** [comment] 2016-04-10 20:14
Update, I'm wrong. Issue was coming from any `require.ensure` in the code and `CommonsChunkPlugin({ children: true})` was used as another plugin. 

@sokra you can reproduce if you add `new webpack.optimize.CommonsChunkPlugin({ children: true})` as a new plugins entry to [test/cases/merging-multiple-entries-shared/webpack.config.js](https://github.com/webpack/extract-text-webpack-plugin/blob/master/test/cases/merging-multiple-entries-shared/webpack.config.js)

Hope that helps. I spend a few hours trying to understand what is happening during `optimize-tree` step, but it is not so easy to figure out the logic. Like mentioned above undefined entry is added at [index.js:219](https://github.com/webpack/extract-text-webpack-plugin/blob/master/index.js#L219).

**Comment by RabidFX** [comment] 2016-04-12 05:44
@szarouski I'm glad you posted this update, I was worried that you found a totally different cause to this bug than me. Have you found any adverse effect with the fix I proposed?
In any case, I'm not sure we can add third-party plugins to extract-text-webpack's test cases. I'll give it a look, but if it's possible, your suggestion could allow me to commit the missing test case in my pull request.

**Comment by erwingaitano** [comment] 2016-04-12 13:28
Seems related https://github.com/webpack/extract-text-webpack-plugin/issues/82

**Comment by szarouski** [comment] 2016-04-16 14:58
@RabidFX, My problem is that I can't understand if code in extract-text-plugin (with or without your fix) is assuming that chunks structure might be modified by other plugins and the only thing which is left is to make sure that out of range indexes are filtered out. That is why I don't know if it is reliable or not to do what is suggested above. I was hoping that **sokra**, or someone who is familiar with webpack internals can find some time to take a look at what is going on and provide some guidance, but looks like we just need to spend more time looking at the issue until we fully understand what is going on.

**Comment by RabidFX** [comment] 2016-04-17 15:32
@szarouski Yes, as you can see on the PR's disucssion thread, @erwingaitano found that simply filtering out of range indexes in optimize-tree seems insufficient. It solves the problem, but apparently creates another one with async chunks. 
I'm not sure a mechanism *should* rely on such out of range indexes however. It could simply be a case of fixing an error revealing another.

**Comment by adrianmc** [comment] 2016-06-05 17:42
I was also following the Webpack Your Bags tutorial and came upon this error. Has there been any development since April, @RabidFX ?

**Comment by RabidFX** [comment] 2016-06-06 20:28
@adrianmc Nothing new... The PR I proposed still fixes the problem, as far as I know, and I have not stumbled upon any adverse effect so far : https://github.com/webpack/extract-text-webpack-plugin/pull/170
I believe we are a bit stuck until an official contributor to the project gives it a look, as CodCov seems to glitch and will not approve the PR...

**Closed** 2016-07-15 20:00 UTC

**Comment by noudadrichem** [comment] 2018-07-10 09:55
@Peeneye Your snippet did not fix this but it did gave me a new error. 
```  Error: chunk commons [entry]
  [name]-[chunkhash].js
  Path variable [chunkhash] not implemented in this context: [name]-[chunkhash].js
  Error: Path variable [chunkhash] not implemented in this context: [name]-[chunkhash].js
      at /Users/noudadrichem/code/[DIR]]/node_modules/webpack/lib/TemplatedPathPlugin.js:50:26
      at /Users/noudadrichem/code/[DIR]]/node_modules/webpack/lib/TemplatedPathPlugin.js:40:23
      at String.replace (<anonymous>)
      at MainTemplate.replacePathVariables (/Users/noudadrichem/code/[DIR]]/node_modules/webpack/lib/TemplatedPathPlugin.js:71:4)
      at MainTemplate.applyPlugins [as applyPluginsWaterfall] (/Users/noudadrichem/code/[DIR]]/node_modules/tapable/lib/Tapable.js:37:47)
      at registerChunk (/Users/noudadrichem/code/[DIR]]/node_modules/chunk-manifest-webpack-plugin/lib/ChunkManifestPlugin.js:29:43)
      at Array.reduce (<anonymous>)
      at registerChunk (/Users/noudadrichem/code/[DIR]]/node_modules/chunk-manifest-webpack-plugin/lib/ChunkManifestPlugin.js:34:27)
      at Array.reduce (<anonymous>)
      at registerChunk (/Users/noudadrichem/code/[DIR]]/node_modules/chunk-manifest-webpack-plugin/lib/ChunkManifestPlugin.js:34:27)
      at Array.reduce (<anonymous>)
      at MainTemplate.<anonymous> (/Users/noudadrichem/code/[DIR]]/node_modules/chunk-manifest-webpack-plugin/lib/ChunkManifestPlugin.js:23:33)
      at MainTemplate.applyPlugins [as applyPluginsWaterfall] (/Users/noudadrichem/code/[DIR]]/node_modules/tapable/lib/Tapable.js:37:47)
      at MainTemplate.<anonymous> (/Users/noudadrichem/code/[DIR]]/node_modules/webpack/lib/MainTemplate.js:77:30)
      at MainTemplate.applyPlugins [as applyPluginsWaterfall] (/Users/noudadrichem/code/[DIR]]/node_modules/tapable/lib/Tapable.js:37:47)
      at MainTemplate.render (/Users/noudadrichem/code/[DIR]]/node_modules/webpack/lib/MainTemplate.js:111:30)

```
